export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: `Sobre`,
  headline: `Trabalhar e morar numa das melhores praias do mundo, administrando um pequeno negócio já bem conceituado.`,
  description: `(Qualificação acima de 9 na booking e AirBnb)`,
  imgStart: false,
  img: "https://res.cloudinary.com/aguadeira/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1676750900/jeri/WhatsApp_Image_2023-01-29_at_08.44.58_perwfo.jpg",
  alt: "Flet Jeriquaquara",
  dark: true,
  primary: true,
  darkText: false,
  buttonLabel: "Get Started",
};
export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: `Descubra`,
  headline: `Flat com 4 apartamentos em pleno funcionamento, altíssimas notas no Booking e outros apps.`,
  description: `Apartamentos completos com cozinha equipada, ar condicionado, recém reformada, em localização perfeita pra quem busca o sossego do Ceará com a belíssima região, que está entre os 10 destinos mais sonhados do mundo, Jericoacoara fica cheia de turistas o ano todo!`,
  imgStart: true,
  img: "https://res.cloudinary.com/aguadeira/image/upload/v1676847105/jeri/WhatsApp_Image_2023-01-29_at_08.44.57_1_qtbyff.jpg",
  alt: "Flet Jeriquaquara",
  dark: false,
  primary: true,
  darkText: true,
};
