export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: `Sobre`,
  headline: `Trabalhar e morar numa das melhores praias do mundo, administrando um pequeno negócio já bem conceituado.`,
  description: `(Qualificação acima de 9 na booking e AirBnb)`,
  imgStart: false,
  img: "https://res.cloudinary.com/aguadeira/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1676750900/jeri/WhatsApp_Image_2023-01-29_at_08.44.58_perwfo.jpg",
  alt: "Flet Jeriquaquara",
  dark: true,
  primary: true,
  darkText: false,
  buttonLabel: "Get Started",
};
export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: `enterprise.company`,
  headline: `"enterprise.enterpriseh`,
  description: `enterprise.enterpriseh2`,

  imgStart: true,
  img: process.env.PUBLIC_URL + "icon-nr13.webp",
  alt: "Car",
  dark: false,
  primary: true,
  darkText: true,
};
